[LT-980_MPARTICLE_OUTGOING]
sailthru/mparticle-outgoing-lambda pull request #1
Opened 2024-05-27 19:03 UTC by kumelahmedbadger

ci/cd config changes, add java orbs, add missing java version.

2024-05-28 19:35 UTC, bge-kernel-panic approved these changes
I don't want to block further deployments if you have something that more or less works here, but there may be ways to further simplify the circleci configuration. See comments.

2024-05-28 19:35 UTC, bge-kernel-panic commented on .circleci/config.yml
> +      - *persist_workspace
todo: I still think we should use the jvm orb to run tests at the very least. Should save you a bit of annoyance with the cache management.

2024-05-28 19:35 UTC, bge-kernel-panic commented on build.gradle.kts
> +    targetCompatibility = JavaVersion.VERSION_17
thought: have you tried with just the `languageVersion.set()` part? I would think it forces the appropriate sourceCompatibility and targetCompatibility

2024-05-28 19:35 UTC, bge-kernel-panic commented on build.gradle.kts
> +    targetCompatibility = JavaVersion.VERSION_17
todo: we should use Java 21 because it will let us use virtual threads to handle HTTP calls. This will require upgrading to a newer Gradle version, which is fine. An example Java 21 program: https://github.com/sailthru/lo-history-data-migrator . It uses Gradle 8.5.

2024-05-29 04:36 UTC, kumelahmedbadger commented on build.gradle.kts
> +    targetCompatibility = JavaVersion.VERSION_17
This is resolved, have upgraded gralde to latest v8.7, the project is now configured to use java 21.

2024-05-30 15:16 UTC, bge-kernel-panic requested changes
Found some problems with how the Lambda zip file is created. See comments.

2024-05-30 15:16 UTC, bge-kernel-panic commented on build.gradle.kts
> -//    id("com.sailthru.gradle") version("v0.7.0")
issue: if we're going to stop using the built-in plugin we _need_ to fix a few things.

1. We need to add `dependencyLocking { lockAllConfigurations() }` somewhere in the build file
2. The version should be set in `settings.gradle.kts` as `SANDBOX`
3. The version needs to be overridden when deploying to production in the circleci configuration using `./gradlew -Pversion=${CIRCLECI_SHA1}`
4. Ideally we would attach the `buildZip` command to the `assemble` lifecycle -
```kotlin
tasks.register<Zip>("buildZip") {
    dependsOn(tasks.classes)
    from(sourceSets.main.get().output)
    into("lib") {
        from(configurations.runtimeClasspath)
    }
}

tasks.assemble {
    dependsOn("buildZip")
}
```
5. In the circleci configuration you probably want to call `./gradlew -Pversion=... assemble` instead of `./gradlew -Pversion=... -x test build` (if you want to build without tests assemble is what you want according to Gradle documentation)

2024-05-30 15:47 UTC, bge-kernel-panic commented on .circleci/config.yml
>            aws-region: DEV_AWS_REGION
question: are you sure this is the correct env var for the region? I think we have a STAGE_AWS_REGION or something similar somewhere...

2024-05-30 15:47 UTC, bge-kernel-panic commented on .circleci/config.yml
> +          from: ~/project/build/distributions/mparticle-outgoing-lambda-1.0-SNAPSHOT.zip
suggestion: pass the version when building in Gradle (./gradlew -Pversion=${CIRCLE_SHA1} assemble) and then you can be sure the zip file will be named `~/project/build/distributions/mparticle-outgoing-lambda-${CIRCLE_SHA1}.zip`.

2024-05-30 15:47 UTC, bge-kernel-panic commented on .circleci/config.yml
>              - test
thought: there is no `deploy_to_prod` yet. It should probably run only when the following filter is true:

```yaml
workflows:
    build_to_prod:
        when:
            and:
                - equal: [ main, << pipeline.git.branch >> ]
                - matches: { pattern: "^v\d+$", value: << pipeline.git.tag >> }
        jobs:
            - deploy_to_prod:
               # ...
```

2024-05-31 08:30 UTC, kumelahmedbadger commented on .circleci/config.yml
>            aws-region: DEV_AWS_REGION
"STAGE_AWS_REGION" does not seem to be the right one, verified this the region is set blank when used with an exception `Invalid endpoint: https://sts..amazonaws.com`

Where as the "DEV_AWS_REGION" works fine setting it to "us-east-1" verified using echo command.
one such reference project using this "DEV_AWS_REGION" **mparticle-webhook-lambda-main**

2024-05-31 14:09 UTC, bge-kernel-panic approved these changes
+1 so you can keep working but please see my comments - especially the one about jcl-over-slf4j. Things will still work regardless but it may be difficult to get logs for some third-party libraries unless this is fixed. I believe the dependency comes from Apache httpcore, which would be request logs - which are sometimes quite useful when debugging weird AWS call issues.

2024-05-31 14:09 UTC, bge-kernel-panic commented on .circleci/config.yml
>            aws-region: DEV_AWS_REGION
OK I found the right one
Try `AWS_DEFAULT_REGION`
For that though you'll need the `AWS ECR Push` context
Alternatively you can grab the `AWS Region` context, then it's in env var AWS_REGION

2024-05-31 14:09 UTC, bge-kernel-panic commented on build.gradle.kts
> +version = "SANDBOX"
quibble: this should typically go in `settings.gradle.kts`

2024-05-31 14:09 UTC, bge-kernel-panic commented on build.gradle.kts
> +    implementation(platform("software.amazon.awssdk:bom:2.25.60"))
quibble: I'm a bit miffed we're getting `commons-logging` pulled in presence of slf4j. Try adding this in the dependencies section:
```kotlin
    modules {
        module("commons-logging:commons-logging") {
            replacedBy("org.slf4j:jcl-over-slf4j")
        }
    }
    // ...
    implementation("org.slf4j:jcl-over-slf4j:1.7.32")
```

What this does:
1. Declare that commons-logging is replaced by jcl-over-slf4j
2. Include jcl-over-slf4j in your project

2024-06-03 07:07 UTC, kumelahmedbadger commented on build.gradle.kts
> +    implementation(platform("software.amazon.awssdk:bom:2.25.60"))
resolved.

2024-06-03 07:08 UTC, kumelahmedbadger commented on build.gradle.kts
> +version = "SANDBOX"
I believe this goes in build, there is no such project version property in setting.gardle.kts

2024-06-04 21:11 UTC, bge-kernel-panic commented on build.gradle.kts
> +version = "SANDBOX"
sorry after checking it goes in `gradle.properties` - this way it can be overridden easily by the -P flag from Gradle.

2024-06-06 10:02 UTC, merged