[LT-1115] Accept multiple events
sailthru/mparticle-outgoing-lambda pull request #10
Opened 2024-07-12 06:19 UTC by jc-sailthru

2024-07-12 15:25 UTC, bge-kernel-panic requested changes
I believe it's pretty important to make use of the timestamp lest trouble occur when we process a backlog of messages.

2024-07-12 15:25 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MParticleClient.java
todo: add the timestamp here:

```java
batch.timestampUnixtimeMs(parseTimestamp(message.getTimestamp()));
// ...

private Long parseTimestamp(String timestamp) {
    try {
        if (!Strings.isEmpty(timestamp)) {
            final ZonedDateTime dt = ZonedDateTime.parse(timestamp, ISO_DATE_TIME);
            return dt.toInstant().toEpochMillis();
        }
    } catch (DateTimeParseException e) {
        // maybe log the error
    }
    return null;
}
```

2024-07-15 22:02 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MParticleClient.java
Good catch, this is done

2024-07-15 22:07 UTC, bge-kernel-panic approved these changes
+1

2024-07-15 22:43 UTC, merged