feat: [LT-1141] log too large messages
sailthru/mparticle-outgoing-lambda pull request #14
Opened 2024-09-20 22:48 UTC by bge-kernel-panic

Any message which is too large will be logged and sent to DLQ. Metrics will be sent to CloudWatch through the use of the aws-embedded-metrics library (didn't want to pull all of powertools because it pulls log4j2 of all things...)

We also log the exact message client ID + mpId or email (whichever we find)

Had to reorganize some code to allow this, sorry.

2024-09-22 23:07 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +    private static final int MAX_MPARTICLE_MESSAGE_LENGTH = 256 * 1000; // 256 kb - rounded down in case they messed up
I'd like to be sure on the exact limit in case they do support 256 * 1024 because this should be relatively easy to figure out and if it is the higher number we may prevent a significant number of messages going through for no reason.

2024-09-23 05:11 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +        if (!mparticleDisabled) {
Can we add a log message that the lambda is disabled

2024-09-23 05:15 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +                        e.getOriginalMessage().getClientId(),
In my opinion, the naming of "getOriginalMessage" is too close to getMessage so is confusion to read.  I think it would be better to extract the details from the instance of MParticleOutgoingMessage and store in PayloadTooLargeException.

2024-09-23 05:15 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +        if (!mparticleDisabled) {
Nevermind, I see you added one below

2024-09-23 05:18 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +                metrics.mark(context, sqsMessage, "MessageTooLarge", 1);
Can we add a unit test to verify the right metrics are being set when expected?

2024-09-23 05:20 UTC, jc-sailthru requested changes
Nice work overall, just a couple of comments

2024-09-23 13:36 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +                        e.getOriginalMessage().getClientId(),
What about renaming to `getPayload()`? We could extract exactly what we want in the exception but I dislike doing this since it basically decides what the exception handler will need ahead of time - which can lead to annoying refactors.

2024-09-23 13:37 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +                metrics.mark(context, sqsMessage, "MessageTooLarge", 1);
Hm. I'll have to look up how to do this, by default the metrics get sent out to System.out but maybe there's a way I can force them to go elsewhere. I will at least add a simple test with a mock which won't tell us much but I guess it's better than nothing.

2024-09-23 13:38 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +    private static final int MAX_MPARTICLE_MESSAGE_LENGTH = 256 * 1000; // 256 kb - rounded down in case they messed up
I'd agree in general but at the same time keep in mind this is an early test - at this point, we just want to see whether this problem will pop up at all. If we can stay below 256,000 bytes we know for sure we won't have issues. We can always adjust later.

I'll open a ticket to get us to confirm the actual boundary.

2024-09-23 14:49 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +    private static final int MAX_MPARTICLE_MESSAGE_LENGTH = 256 * 1000; // 256 kb - rounded down in case they messed up
Ticket opened: https://sailthru.atlassian.net/browse/LT-1236

2024-09-23 21:01 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +                        e.getOriginalMessage().getClientId(),
That would work

2024-09-24 12:44 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +                        e.getOriginalMessage().getClientId(),
Done :)

2024-09-24 16:22 UTC, jc-sailthru approved these changes

2024-09-24 16:38 UTC, merged

2024-09-25 05:18 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +    private static final int MAX_MPARTICLE_MESSAGE_LENGTH = 256 * 1000; // 256 kb - rounded down in case they messed up
I was successfully able to send a request of 256 * 1024 KB.  See https://sailthru.atlassian.net/browse/LT-1236 comments.