[LT-984] Send messages to mParticle
sailthru/mparticle-outgoing-lambda pull request #8
Opened 2024-07-02 06:56 UTC by jc-sailthru

2024-07-02 13:51 UTC, bge-kernel-panic requested changes
Please review the exception handling, I think it needs a bit more thought.

2024-07-02 13:51 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MParticleClient.java
> +        return apiClient.createService(EventsApi.class);
question: don't we want to reuse the same apiClient across calls? If there's any kind of heavy initialization here it'll be expensive to do this every time a new client is created (see my comments on MParticleClient creation below)

2024-07-02 13:51 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +    }
thought: this is not thread-safe; not sure this is an issue in Lambda code, it depends on whether the same VM could be used to handle multiple parallel invocations (I don't think this is the case, but can't find definitive documentation one way or another).

In theory the variables should at least be `volatile` and guarded with a synchronized block. Or even better, have the client passed as a constructor parameter - this way the object isn't even available until the dependencies are as well. That would mean initializing the whole stack in the `SQSLambdaHandler` (which would serve as a poor person's dependency injection container) but synchronization would only be needed there instead of spread around.

Or you could even initialize the mParticleClient and messageSerializer in the constructor here, similar to how ObjectMapper is initialized in the MessageSerializer constructor. I mean why not? There isn't that much point in doing lazy initialization since if your MessageProcessor is initialized it _will_ need the client and the serializer most likely...

2024-07-02 13:51 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +            }
issue: shouldn't RuntimeException be marked as a batch failure as well? Otherwise the whole batch will get retried if there's any error of any sort that's not a RetryLaterException (for instance some socket timeout). This will include messages that were successfully processed and will cause duplicate events.

Not to mention the `IllegalArgumentException` you throw if the API keys aren't supplied (and consider using a specific exception for that) - those should be treated as "success" but they should cause a log entry to be emitted

2024-07-02 13:51 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MParticleMessage.java
> +    private String profileEmail;
todo: couple of things here:
1. Make sure that same class exists in the mparticle-outgoing project.
2. You probably want to add the profileId as well - though maybe that would be passed in the `additionalData`
3. There has been some discussion on #lo-team-st about adding the mparticle ID as an extid field in profiles and making it available in each message. I would add mParticleId as a field here as well (String is fine, I have no idea what the actual format will be but if we use string it's a pretty safe bet we'll be able to pass whatever we need).
4. Please check for the mparticle ID if there's anything in the mparticle docs that prescribes a specific field name for it.

2024-07-02 13:51 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +        return messageProcessor;
thought: as mentioned before I wouldn't lazy-initialize any of this - just new the `MessageProcessor` in the constructor.
If you want to be able to override it for unit tests the setter works, or you can provide an additional constructor.

2024-07-02 20:08 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MParticleClient.java
> +        return apiClient.createService(EventsApi.class);
No because each message contains the key/secret for API authentication

2024-07-03 01:09 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MParticleMessage.java
> +    private String profileEmail;
1: I was going to do #1 as part of the next ticket which passes this information to the SQS queue.
2: I would just be adding the profileId into additionalData anyway so might as well be put in there on the mparticle-outgoing side.
3: This hasn't been finalised yet so I'd like to leave this out of scope and work on this when it is required.
4: Same as above

2024-07-03 02:51 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +        return messageProcessor;
Fair point this is done

2024-07-03 02:51 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MessageProcessor.java
> +    }
Fair enough, have moved to the constructor

2024-07-03 03:32 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +            }
That is a good point.  I have changed to catch Exceptions so we catch everything.

2024-07-03 13:53 UTC, bge-kernel-panic requested changes

2024-07-03 13:53 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +            } catch (Exception e) {
issue: couple of things here:
1. This also catches NoRetryException which should not be added to the batchItemFailures
2. It's better form to catch exactly what you want - you don't actually want to catch _all_ checked exceptions + all runtime exceptions - there are only two checked exceptions possible here: `NoRetryException` and `RetryLaterException`. The former should have its own catch block, and the latter should have the same treatment as `RuntimeException`.

suggestion:
```java
} catch (NoRetryException e) {
    // log the message or something
} catch (RetryLaterException | RuntimeException e) {
    // log the message
    batchItemFailures.add(new SQSBatchResponse.BatchItemFailure(sqsMessage.getMessageId());
}
```

2024-07-03 13:53 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/exception/NoRetryException.java
> +public class NoRetryException extends Exception {
thought: consider adding subclasses, say
* AuthenticationKeyNotProvidedException
* AuthenticationSecretNotProvidedException
* UnparseablePayloadException

this is not mandatory but it'll read better; you can still catch/throws NoRetryException

2024-07-03 13:53 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MParticleClient.java
> +        LOGGER.info("Attempting to send batch: {} for message: {}", batch, message);
question: should this be DEBUG level?

2024-07-03 13:53 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MParticleClient.java
> +            //Retry for all IOExceptions
thought: may be a good idea to log the error here, together with the payload that was sent, at least at the DEBUG level.

2024-07-03 13:53 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +        final List<SQSBatchResponse.BatchItemFailure> batchItemFailures = new ArrayList<>();
thought: might be a good idea to initialize the logging level here according to some env variable, so we can turn debug logging on or off easily.
Something like
```java
final String levelString = System.getEnv("LOG_LEVEL");
if (levelString != null) {
  try {
      final Level level = Level.valueOf(levelString);
      ((LoggerContext) LoggerFactory.getILoggerFactory()).getLogger(Logger.ROOT_LOGGER_NAME).setLevel(level);
  } catch (IllegalArgumentException e) {
      LOGGER.warn("Supplied log level {} not known", levelString);
  }
}
```

2024-07-03 20:14 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +            } catch (Exception e) {
Done

2024-07-03 20:15 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MParticleClient.java
> +            //Retry for all IOExceptions
It gets logged in the stacktrace in the root level catch block

2024-07-03 20:18 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/exception/NoRetryException.java
> +public class NoRetryException extends Exception {
Nice idea, have implemented

2024-07-03 20:39 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/MParticleClient.java
> +        LOGGER.info("Attempting to send batch: {} for message: {}", batch, message);
Done

2024-07-03 20:54 UTC, jc-sailthru commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +        final List<SQSBatchResponse.BatchItemFailure> batchItemFailures = new ArrayList<>();
Done

2024-07-03 21:36 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/SQSLambdaHandler.java
> +        setupLogLevel();
quibble: since it's already set up in the `static{}` initializer above there's no need to call this again.

2024-07-03 21:36 UTC, bge-kernel-panic commented on src/main/java/com/sailthru/sqs/MParticleClient.java
> +            //Retry for all IOExceptions
quibble: would suggest logging the message payload as well at the debug level then. Could be done at the toplevel. The idea is that if we can see the payload it'll be easier to figure out why we got the exception...

2024-07-03 21:36 UTC, bge-kernel-panic approved these changes
+1. Couple of minor items, feel free to address them later.

2024-07-04 02:05 UTC, merged